default: &default
  adapter: postgresql
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dragon_make_development
test:
  <<: *default
  database: dragon_make_test
production:
  <<: *default
  database: dragon_make_production
  username: dragon_make
  password: <%= ENV['dragon_make_DATABASE_PASSWORD'] %>
